CREATE TABLE users(
    id SERIAL PRIMARY KEY, -- 使用者ID
    name VARCHAR(255) NOT NULL, -- 使用者名稱
    password VARCHAR(255) NOT NULL, -- 使用者密碼
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

/*
SERIAL：自動遞增的整數，通常用於主鍵
PRIMARY KEY：主鍵，唯一標識每一行資料
VARCHAR(255)：可變長度的字串，最大長度為255個字
TIMESTAMP：時間戳記，表示日期和時間
DEFAULT CURRENT_TIMESTAMP：預設值為當前時間
ON UPDATE CURRENT_TIMESTAMP：當資料行被更新時，自動更新為當前時間
*/